# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2022-04-10 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artsy_id', models.CharField(db_index=True, help_text=b'Artsy ID of artwork', max_length=128)),
                ('date_selected', models.DateField(auto_now_add=True, db_index=True, help_text=b'Date of when painting was selected', unique=True)),
            ],
        ),
    ]
