# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2022-04-10 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painting_per_day', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='artist',
            field=models.CharField(db_index=True, default='', help_text=b'Artist of painting', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='painting',
            name='date',
            field=models.CharField(db_index=True, default='', help_text=b'Date of painting', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='painting',
            name='image_link',
            field=models.CharField(db_index=True, default='', help_text=b'Link to image of painting', max_length=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='painting',
            name='artsy_id',
            field=models.CharField(db_index=True, help_text=b'Artsy ID of artwork', max_length=128, unique=True),
        ),
    ]
